### ISSUE TITLE
[Upgrade Request] Appraisal - Scrapped

### ISSUE THREAD

**Issue by coty9090** [peace-maker/smrpg#183]
Appraisal - Lowers the skill points cost of every upgrade except this one. lvl 1, 1%. lvl 2, 2%.

**Comment by peace-maker** [comment]
This isn't really applicable, because the credits are integers and no floating-point numbers. 1% less credit cost wouldn't change the amount as expected due to rounding.

I don't think changing the credits to floats would be good. You'd easily lose track of you can buy and what not if all upgrades cost 2,35 credits etc.

**Comment by coty9090** [comment]
Alright, thanks for the info!
