### ISSUE TITLE
Trouble with rpgmenu_sorting

### ISSUE THREAD

**Issue by kalle4000** [peace-maker/smrpg#21]
Hi, very good rpg plugin!

I'm having trouble with configuring the rpgmenu_sorting. 
I would like the health upgrade, hp regen (with others) to be the first options in the upgrade menu, so in the RpgUpgradesMenu-section in the rpgmenu_sorting.txt I edit it like this: 

	"RPGUpgradesMenu"
	{
		"item"		"health"
		"item"		"regen"
	} 
But nothing changes in the upgrade menu (upgrades are still loaded alphabetically), and error logs says:
"Could not load rpg menu config (file "addons/sourcemod/configs/smrpg/rpgmenu_sorting.txt": Line contained too many invalid tokens)"

So obviously I'm doing something wrong. What do I need to write instead, to make it work?  :)

**Comment by peace-maker** [comment]
That looks syntactically fine. Maybe you messed up somewhere else in the file?

Due to the way topmenus cache the names of items you have to prefix the short name of the upgrade:
 * RPGUpgradesMenu: rpgupgrade_xxx
 * RPGSellMenu: rpgsell_xxx
 * RPGUpgradeSettingsMenu: rpgupgrsettings_xxx
 * RPGHelpMenu: rpghelp_xxx

**Comment by kalle4000** [comment]
Thank you peace-maker, changing the prefix to   "item"      " rpgupgrade_health", and so on, solved it. Thank you :)
