### ISSUE TITLE
rpg levels next to name (not sure if we should put it here)

### ISSUE THREAD

**Issue by Thomasdavid097** [peace-maker/smrpg#232]
hello there, I was wondering if there was away to put rpg levels next to the players names other then the tags that we have on the server, many players have asked this but I am unsure if there is already away or?

sometime like:
[lvl 10] Thomasdavid097: text

I think this would be a nice thing to see added, if not already done. 
Thanks (sorry if it's under the wrong sub forum)

**Comment by peace-maker** [comment]
Other than the tags? So you want a player name to appear like
[OtherTag] [LVL 20] Name : text
In addition to other chat tag plugins?
Which chat tag plugin do you use?

**Comment by Thomasdavid097** [comment]
I use TOGs Chat Tags plugin, but ya I just want it something like [LVL] 20 name with out the tags

**Comment by coty9090** [comment]
I like that suggestion. +1

**Comment by peace-maker** [comment]
There it is. This adds a chat tag like `[Rank 2]` for the first X ranked players (X can be controlled by a cvar) and a chat tag with the current rpg level like `[LVL 62]`.
Let me know if there's something missing. Due to a incompatibility between the chat processors, there is one version for the old [Simple Chat Processor](https://forums.alliedmods.net/showthread.php?t=198501) and one for the enhanced, recommened [Chat Processor](https://forums.alliedmods.net/showthread.php?t=286913). Check the snapshot build for the `smrpg_chattags_scp.smx` or `smrpg_chattags_cp.smx` respectively.
