### ISSUE TITLE
Exp earned per kill printed on the screen CSGO Issue

### ISSUE THREAD

**Issue by robin955** [peace-maker/smrpg#254]
removed several plugins, keyhint is also on by default and there is no cvar to remove it? and you ahve to type rpg and manually remove an annoying thing that sits on the screen for 24/7, what were you thinking? (just saying, nobody wants to see it)

annyway, everytime i kill someone it logs chat exp like this, i've re compiled the plugins and i removed the keyhint and chatxpstats as i got no clue what chatxpstats actually is, as this was happening even with it removed.

and there is no cvar for this, this needs to be off by default, cant have it print a big message everytime you get exp. someone else got this out of the way? should make a cvar for this.
[img]http://image.prntscr.com/image/43dea5c3241540a4baaa9f8a56a734af.png

**Comment by peace-maker** [comment]
Hey dude, I'm afraid to tell you since you did your research so well, but I tried to keep the [url=https://github.com/peace-maker/smrpg#installation]install instructions[/url] as clear as possible with what additional features you want. I assumed the `smrpg_exp_notice` convar handles that message as [url=https://github.com/peace-maker/smrpg/wiki/ConVar-list#smrpg-core]documented[/url].

**Comment by robin955** [comment]
thanks, had not seen anything about the convar list.

so what does chatxpstats.smx do then?

**Comment by peace-maker** [comment]
From the readme
> smrpg_chatxpstats - Display infos in chat about gained experience for a kill or during the whole last life.

That has been added before the keyhint plugin supported CSGO, so you still have some info about your progress there.
