### ISSUE TITLE
Request: DB field user_online: 1/0 (true/false)

### ISSUE THREAD

**Issue by Hetachi** [peace-maker/smrpg#287]
So recently I have been working around couple of nodejs apps that integrate smrpg with my website, and I ran into issues that users could buy or sell rpg credits / levels / xp trough website, and then get them all back if they disconnected from the server, since server saves data when a players leaves the server, so any changes to the player field before the player has disconnected are lost.

Could you please make an addition if its not too hard or a simple side plugin for it ?

What I am looking for is a field in database that would indicate if user is online right now in server or not, then I could ask them to disconnect in order to continue with a certain action that would change their RPG stats.

**Comment by peace-maker** [comment]
You already suggested that two years ago in #71 and we came up with solutions on how you can check if a player is online.
Keeping a list of connected players in a database isn't something I want to deal with in this plugin, since it's not essential to it working. Maybe you can find some playtime tracking plugin which gives you access to that in a database.
