### ISSUE TITLE
Some modules didn't respect smrpg_%upgrade_name%_maxlevel cvar

### ISSUE THREAD

**Issue by Z-RAY-Z** [peace-maker/smrpg#291]
I was face the issue - some modules are ignoring smrpg_%upgrade_name%_maxlevel cvar. Error logs are clear.
For example - stealth module had smrpg_steath_maxlevel set to 10, but in buy menu i was see only 5
https://imgur.com/a/TxvKyYM (look at Невидимость)
I was try:
> Reload "bad" module.
> Change cvar via sm_cvar command.
> sm plugins reload smrpg.smx
No one help.
I can't change Max Level even with admin menu.
https://imgur.com/a/a0Tk6e7
Note: Невидимость=stealth, Макслевел=max level, барьер=barrier
This issue plagued even modules form private requests.

**Comment by Z-RAY-Z** [comment]
I was proper look at config files nad set smrpg_ignore_level_barrier value 1 solve issues.

**Comment by peace-maker** [comment]
I've removed the maxlevel limit from most upgrades now. They weren't necessary anymore, since you were able to configure the increasing rate of the upgrade effects yourself, but just were never removed. Server admins need to make sure their configuration makes sense together with the maxlevel they set.
