### ISSUE TITLE
plugin resets players without any admin interference?

### ISSUE THREAD

**Issue by DraxB** [peace-maker/smrpg#37]
Hi recently I have gotten several complaints on a server where people claim that their rpg level has been reset to 0. 

I recently updated sourcemod to 1.7, and I'm still using the plugins back from 2014 (sourcemod 1.6). Do you think that could be the reason causing it? 

Everything else works as it should, but yeah defiantly sounds weird that it just resets players.

Note that it is not all players, but players are claiming that it has been reset back to 0.

**Comment by peace-maker** [comment]
There are several possibilities to have a player reset. You could have configured a maximal level after which the player would get reset. The player reset its own stats through the menu. The resetstats plugin would reset all players at once.

But all those cases would get logged. Have you searched for the steamid of the player who claims to be reset in the source of logs? Any errors in the logs?

If the server fails to authenticate the player with steam, he'd never have his stats loaded too, so maybe there's been connection problems with the steam authentication backend. That would only be temporary though and the player would get his old level the next time he joins and gets authenticated correctly.

You should still update the plugin. Lots has changed since 2014;)

**Comment by DraxB** [comment]
Okay, I'm probably going to wait with the update since we have a scheduled reset anyway. I was planning to do it there anyway.

In terms of the logs, are they any specific log that would be best to look for this? Or do you just refer to console.log. AFAIK there aren't any error in the logs that suggests something is wrong, the people  that were complaining about it, said they had a certain level weeks/months back. Since I have hlxstats I can see that it is somehow weird when a specific person got 400 kills and was suddenly level 0 again. I was planning on searching his steam in console.log, but the file had never been reseted, so the file was to big to open..

Thanks for the help regardless.

**Comment by peace-maker** [comment]
No, i'm referring to the logs files in addons/sourcemod/logs.
Ah, players are removed when they don't connect for 30 days by default (smrpg_player_expire convar). You can set that to 0 if you want to keep every single player forever in your database.

**Comment by DraxB** [comment]
Oh that would defiantly explain why, the players who lost exp metioned they hadn't been on for some time. 

I know this sounds rather stupid, but where can I change this convar? I can't seem to find it anywhere...
