### ISSUE TITLE
Increase Clipsize does not accept values lower than 1

### ISSUE THREAD

**Issue by DeewaTT91** [peace-maker/smrpg#389]
I set the clipsize increase for some weapons lower than 1. 
For example for the shotgun I wanted to add 1 ammo every 2 levels. So I set it to 0.5, but it doesn't add any levels at all, regardless how high the upgrade level gets.

**Comment by WanekWest** [comment]
This looks quite logical, because the very function of installing a cartridge for a weapon does not provide for the installation of a cartridge.

`void SetClientWeaponReserveAmmo(int client, int weapon, int primaryAmmo=-1, int secondaryAmmo=-1)`

And also when reading the config, Get Num is called, which will return an int value.
`iClipIncrease = hKV.GetNum(NULL_STRING, 0);`

**Comment by peace-maker** [comment]
@WanekWest You're right, the upgrade didn't support rational numbers. I've added support for them now. Thank you for the analysis!
