### ISSUE TITLE
Longjump plugin

### ISSUE THREAD

**Issue by daswood** [peace-maker/smrpg#63]
How do I set the long jump plugin to gain velocity as you jump. I poured over the source for the longjump upgrade,  but couldn't figure it out.

**Comment by peace-maker** [comment]
It already adds up, if you do the bunny hopping correctly. You might have to set sv_allowbunnyhopping to 1.
Which game btw?

**Comment by maxgraham** [comment]
I have the same problem, it doesnt matter how you jump, it wont be bunnyhopping. Let me tell you how it works, and how it should work.

So in CS: Source when i played rpg 6 years before, we used not a plugin, at least it didnt required sourcemod neither eventscript, it was like mani admin plugin or the old zombie mod,, we downloaded it from "www.cssrpg.com" (which is now doesnt exist), anyways.
When you pressed Space, it gave you a boost, then when you almost landed pressed again, it gave you again boost and after 2-3 jump you were sooo freaking fast and you could do bunnyhop without even the bunnyhop technique.

Here in CS:GO (he is talking about CS:GO as well), something wrong, because the first jump gives you boost, but the second and the rest will be normal jump without boost. I tried autojump plugins, and the same, i am holding space, the first jump gives you boost but the rest is just simple jump, and i repeat its an autojump plugin so the jumps are perfect.

Can you please kindly fix this? The Longjump is kinda useless in this format, maybe its working in CS:S but in CS:Go its not working properly.

**Comment by peace-maker** [comment]
csgo enforces the server maxspeed when the player is on the ground. Try that unlocker https://forums.alliedmods.net/showthread.php?t=255298

**Comment by maxgraham** [comment]
thank you very much! You should attach it to the plugin by default

**Comment by peace-maker** [comment]
I'll add a link to the readme. Thanks for bringing it up!
