### ISSUE TITLE
[Request] Mysql database extra column with status named online or not 1/0

### ISSUE THREAD

**Issue by Hetachi** [peace-maker/smrpg#71]
I am not nearly smart enough to make this kind of adjustments in sourcepawn code...
So I am asking here perhaps you could implement this if it's not too much of a hassle?

I am deving a control panel for the SM-RPG, but I am having trouble getting the info if player is online or not at that exact point... So this would really help me to make sure the player is offline to add credits / levels / exp and it would be saved and loaded upon connection. Otherwise it might set level to 50 and players reconnects just to lose those and be reset back to the original state, as the server by default saves data every 150 sec or on disconnect.

So far I have tried to pull game from steam, and determine if the player is in a game or not, but this isn't working as it can be abused. If a player is not in server, and logs into panel it checks with steam, steam says nope he is not in 740 game, after he has logged in the control panel it's quite the hassle to contact steam again and again to just make sure the player is in fact not in the game.

I hope you understand and can help me.

Thank you so much.

**Comment by peace-maker** [comment]
You could check the server using A2S_PLAYER queries. You'd just get the player name though, so it's only worth a warning. You would only really need to make sure the exact player you're editing isn't on the server after submitting the form, so i'd say it's acceptable. Using some asynchronous calls, you could even keep the user in the form until the player disconnects.

Keeping such an "online" state sane accross server crashes is bad. How about adding a command like "smrpg_db_reload_player <steamid>" to replace the current state of the player with the one from the database. So you could send a rcon command to the server after editing a player and have it updated immediately.

Or we could add another timestamp like "lastdisconnected", which would be set on disconnect, so you can compare the "lastseen", which gets updated everytime the stats are saved, with the "lastdisconnected". If `lastseen > lastdisconnected` and lastseen wasn't more than 150 seconds ago, the player is online.

**Comment by Nobody-x** [comment]
Else the xp/credit system can be like "On connected : X xp and Y Credits" then get var like "sessionXp" and "sessionCredit", for the running session all is like X + sessionXp and Y + sessionCredit. when you save to the database, you only add the session value to the actual DB value. You can also put a refresh admin command, and a refresh at save.

**Comment by Hetachi** [comment]
Yea I think that would be an awesome thing, just do the thing that's easier for you.

**Comment by peace-maker** [comment]
> Else the xp/credit system can be like "On connected : X xp and Y Credits" then get var like "sessionXp" and "sessionCredit", for the running session all is like X + sessionXp and Y + sessionCredit. when you save to the database, you only add the session value to the actual DB value. You can also put a refresh admin command, and a refresh at save.

That would require an additional query before saving to check for the current level and experience and calculate the correct level up for the gained experience since the last save. If the player was reset to level 1 and was level 100 before, he'd get the experience he earned while still being level 100 added to his level 1, which would let him level up much quicker again right away. He wouldn't be able to get those frags and experience with level 1. This can't be consistent and might end up in strange states.

I'd rather not support messing with the database while a player is online. I'll add that `lastdisconnected` field. Are you going to publish that webapp @Hetachi ?

**Comment by Hetachi** [comment]
@peace-maker 

At the current state no, but I do plan to release a public version once I have sorted everything out in my version, as the current my version is not even nearly finished and will require lots of work before I can release it. I might also make a github repo, and allow everyone to participate with it. But no promises though :smile:

**Comment by peace-maker** [comment]
Well after implementing that `lastdisconnected` column, i noticed that the `lastseen` actually is nearly enough. The stats are saved when a player disconnects, so the `lastseen` column would be the same as the `lastdisconnected` one when the player disconnects. Instead of putting useless info in the database (well, only useful to some thirdparty app), you're fine with checking if the `lastseen` timestamp was less than 150 seconds ago and there is a player with the same name on the server. That way you can check if the player is online or if it's save to edit the stats in the database.
You don't have to use steamworks to check that. Check out https://github.com/koraktor/steam-condenser or [CServerInfo.php](https://github.com/GameConnect/sourcebansv1/blob/master/web_upload/includes/CServerInfo.php)

**Comment by Nobody-x** [comment]
Why not just put a column connected to 1 when a player connect and to 0
when he disconnect ?

**Comment by peace-maker** [comment]
That would leave the connected column at "1" for all connected players when the server crashes. Such volatile state should stay in the server and don't get put in a database.

**Comment by Hetachi** [comment]
That's the big problem, and it seems there is no real fix or thing to add, just to use what you already wrote there.
